blog/api/urls.py
#!/usr/bin/env python

# encoding: utf-8

'''
 
@author: wersonliu

@contact: wersonliugmail.com
 
@time: 2018/1/23 17:52
 
'''
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^posts/$', views.PostListView.as_view(), name='post_list'),
    url(r'^posts/(?P<pk>\d+)/$', views.PostDetailView.as_view(),
        name='post_detail')
]

blog/urls.py
#!/usr/bin/env python

# encoding: utf-8

'''
 
@author: wersonliu

@contact: wersonliugmail.com
 
@time: 2018/1/20 16:37
 
'''
from django.conf.urls import url

from . import views

from rest_framework import routers

# 网址和处理函数的关系
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # 每一个页面对应一个url处理器
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # 配置归档路径下的文章
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search, name='search')
    url(r'^share/(?P<pk>\d+)/$', views.post_share,
        name='post_share'),
    url(r'^contact', views.contact, name='contact')

]
# #  博客的api构建法
# from .views import PostViewSet
#
# router = routers.DefaultRouter()
# router.register(r'post', PostViewSet)

comments/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
   File Name：     urls
   Author :       aaa
   date：          2018/1/23
-------------------------------------------------
"""
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns=[
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

djblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

from rest_framework import routers as blog_router

# 项目主url
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),

    # 博客的api构建法
    # url(r'^api/', include('blog.api.urls', namespace='api'))
    # url(r'^api/', include(blog_router.url))
    url(r'^account/', include('account.urls'))
]

blog/models.py
from django.db import models

# Create your models here.
# blog/models.py
import markdown
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import strip_tags
# from django.core.urlresolvers import reverse
from django.urls import reverse

# api拓展
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted((item, item) for item in get_all_styles())


# 创建文章,标签等模型
class Category(models.Model):
    """
    Django 要求模型必须继承 models.Model 类。
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了分类名 name 的数据类型，CharField 是字符型，
    CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
    Django 内置的全部类型可查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """

    # 文章标题
    title = models.CharField(max_length=70)

    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    body = models.TextField()

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True)

    # 使用摘要还有第二种方法  truncatechares模板过滤器
    def save(self, *args, **kwargs):
        # 如果没有摘要,从文本主题截取54个字符赋给excerpt
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Post, self).save(*args, **kwargs)

    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。

    # 一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是
    # ForeignKey，即一对多的关联关系。
    category = models.ForeignKey(Category)
    # 1篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用
    # ManyToManyField，表明这是多对多的关联关系,文章可以没有标签
    tags = models.ManyToManyField(Tag, blank=True)
    views = models.PositiveIntegerField(default=0)
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(User)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    # 排序属性
    class Meta:
        ordering = ['-created_time']

    # 增加文章阅读数的方法
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

# # 储存评论
# class Comment(models.Model):
#     # 哪篇文章的评论
#     post = models.ForeignKey(Post, related_name='comments')
#     # 评论人的名字
#     name = models.CharField(max_length=80)
#     # 评论人邮箱
#     email = models.EmailField()
#     # 评论内容
#     body = models.TextField()
#     # 评论时间
#     created = models.DateTimeField(auto_now_add=True)
#
#     class Meta:
#         ordering = ['created']
#
#     def __str__(self):
#         return 'Comment by {} on {}'.format(self.name, self.post)

comments/models.py
from django.db import models

# Create your models here.
from django.db import models


# 储存评论
class Comment(models.Model):
    # 哪篇文章的评论
    post = models.ForeignKey('blog.Post')

    # 评论人的名字
    name = models.CharField(max_length=80)
    # 评论人邮箱
    email = models.EmailField()
    # 评论内容
    text = models.TextField()
    url = models.URLField(blank=True)
    # 评论时间
    created_time = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     ordering = ['created']

    def __str__(self):
        return self.text[:20]

blog/forms.py
#!/usr/bin/env python

# encoding: utf-8

'''
 
@author: wersonliu

@contact: wersonliugmail.com
 
@time: 2018/1/23 11:47
 
'''

from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

blog/api/views.py
#!/usr/bin/env python

# encoding: utf-8

'''
 
@author: wersonliu

@contact: wersonliugmail.com
 
@time: 2018/1/23 17:49
 
'''

from rest_framework import generics
from ..models import Post
from .serializers import PostSerializer


class PostListView(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class PostDetailView(generics.RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

blog/views.py
from django.shortcuts import render

# Create your views here.

import markdown
from django.shortcuts import render, get_object_or_404
from .forms import EmailPostForm
from comments.forms import CommentForm
from .models import Post, Category, Tag
from django.db.models import Q
# q对象,查询表达式
# 改写类视图函数
from django.views.generic import ListView, DetailView
from django.core.mail import send_mail


# request 是django封装好的http请求,返回一个http响应给用户
class IndexView(ListView):
    # 我要获取的模型是post
    model = Post
    template_name = 'blog/index.html'
    # 这个变量会传递给模板
    context_object_name = 'post_list'
    paginate_by = 3


# def index(request):
#     # return HttpResponse("欢迎")
#     # 以时间倒序查询文章,存在变量里
#     post_list = Post.objects.all().order_by('-created_time')
#     # return render(request, 'blog/index.html', context={
#     #     'title': '我的博客',
#     #     'welcome': '欢迎光临'
#     # })
#     # post_list=Post.objects.filter(created_time__year=year,
#     #                               created_time__month=month).order_by('-created_time')
#
#     return render(request, 'blog/index.html', context={
#         'post_list': post_list
#     })


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


#
# class ArchivesView(ListView):
#     model = Post
#     template_name = 'blog/index.html'
#     context_object_name = 'post_list'
#
#     def get_queryset(self):
#         year = self.kwargs.get('year')
#         month = self.kwargs.get('month')
#         return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
#                                                    created_time__month=month)
# 详情页的类视图函数写法,但是没有引用
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.markdown(
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
            ])
        post.body = md.convert(post.body)
        post.toc = md.toc

        return post

    # 显示评论数据的方法
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        # form=
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 每次触发detail函数,就调用阅读增加方法
    post.increase_views()
    # markdown 语法拓展
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    form = CommentForm()
    comment_list = post.comment_set.all()

    return render(request, 'blog/detail.html', context={'post': post,
                                                        'form': form,
                                                        'comment_list': comment_list})


class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


def category(request, pk):
    # 记得在开始部分导入 Category 类
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


def search(request):
    # 获取搜索框的值
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键字'
        return render(request, 'blog/index.html', {'error_msg': error_msg})
    # 数据库包含过滤查询
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'post_list': post_list})


# 分享
def post_share(request, pk):
    post = get_object_or_404(Post, pk=pk)
    sent = ''
    recipient = ''
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({})recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'],
                                                                     cd['comments'])
            send_mail(subject, message, 'wersonlau@163.com', [cd['to']])
            recipient = cd['to']
            sent = True
    else:
        form = EmailPostForm()
        recipient = False
    return render(request, 'blog/share.html',
                  {
                      'post': post,
                      'form': form,
                      'sent': sent,
                      'recipient': recipient}
                  )


def contact(request):
    return render(request, 'blog/contact.html', context={
        'welcome': '足下的到访使小站蓬荜生辉'
    })


# from rest_framework import viewsets
# from .serializer import PostSerializer
#
#
# class PostViewSet(viewsets.ModelViewSet):
#     queryset = Post.objects.all()
#     serializer_class = PostSerializer

templates/blog/contact.html
{% extends 'base.html' %}

{#{% block title %} Share a post {% endblock %}#}

{% block main %}
  <h2>{{ welcome }}</h2>
  <table >
  <tr>
    <th>姓名</th>
    <th>邮箱</th>
    <th>github</th>
  </tr>
  <tr>
    <td>刘伟</td>
    <td>wersonliu@163.com</td>
    <td><a href="https://github.com/WersonLu/djblog" target="_blank">Wersonlu</a></td>
  </tr>
</table>
{% endblock  %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                <span class="share"><a href="{% url 'blog:post_share' post.pk %}">分享</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date"
                              datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{#{% block toc %}#}
{#    <div class="widget widget-content">#}
{#        <h3 class="widget-title">文章目录</h3>#}
{#        {{ post.toc|safe }}#}
{#    </div>#}
{#{% endblock toc %}#}

templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }}阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时没有文章!</div>
    {% endfor %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
{#    django自带的简单分页#}
    {% if is_paginated %}
    <div class="pagination-simple">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"></a>
        {% endif %}
{#        <ul>#}
{#            <li><a href="">1</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">4</a></li>#}
{#            <li><a href="">5</a></li>#}
{#            <li class="current"><a href="">6</a></li>#}
{#            <li><a href="">7</a></li>#}
{#            <li><a href="">8</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">11</a></li>#}
{#        </ul>#}
        <span class="current">第{{ page_obj.number }}页/共{{ paginator.num_pages }}页</span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}    
    </div>
    {% endif %}
{% endblock main %}

templates/blog/share.html
{% extends 'base.html' %}

{#{% block title %} Share a post {% endblock %}#}

{% block main %}
  {% if sent %}
     <h1>邮件分享成功</h1>
     <p>
         文章"{{ post.title }}" 成功的分享到{{recipient}}.
     </p>
  {% else %}
      <h2>通过邮件分享{{ post.title}}</h2>
      <form action="{% url 'blog:post_share' post.pk %}" method='post'>
        {{ form.as_p}}
        {% csrf_token %}
        <input type="submit" value="发送邮件"}/>
      </form>
  {% endif %}
{% endblock  %}